### ISSUE TITLE
NiFi does not start in Docker

### ISSUE THREAD

**Issue by viazovskyi** [influxdata/nifi-influxdb-bundle#40]
Hi, I am using NiFi 1.12.0 running in [docker](https://hub.docker.com/r/apache/nifi). I've tried different versions of NAR (1.9.0-SNAPSHOT, 1.8.0, 1.0), but they all lead to an exception when starting NiFi that stops NiFi.

```
2020-11-02 12:55:38,373 ERROR [main] org.apache.nifi.NiFi Failure to launch NiFi due to java.util.ServiceConfigurationError: org.apache.nifi.controller.ControllerService: Provider org.influxdata.nifi.services.StandardInfluxDatabaseService could not be instantiated
java.util.ServiceConfigurationError: org.apache.nifi.controller.ControllerService: Provider org.influxdata.nifi.services.StandardInfluxDatabaseService could not be instantiated
        at java.util.ServiceLoader.fail(ServiceLoader.java:232)
        at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
        at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
        at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
        at org.apache.nifi.nar.StandardExtensionDiscoveringManager.loadExtensions(StandardExtensionDiscoveringManager.java:156)
        at org.apache.nifi.nar.StandardExtensionDiscoveringManager.discoverExtensions(StandardExtensionDiscoveringManager.java:131)
        at org.apache.nifi.nar.StandardExtensionDiscoveringManager.discoverExtensions(StandardExtensionDiscoveringManager.java:117)
        at org.apache.nifi.web.server.JettyServer.start(JettyServer.java:1048)
        at org.apache.nifi.NiFi.<init>(NiFi.java:158)
        at org.apache.nifi.NiFi.<init>(NiFi.java:72)
        at org.apache.nifi.NiFi.main(NiFi.java:301)
Caused by: java.lang.NoClassDefFoundError: org/apache/nifi/ssl/SSLContextService$ClientAuth
        at java.lang.Class.getDeclaredConstructors0(Native Method)
        at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
        at java.lang.Class.getConstructor0(Class.java:3075)
        at java.lang.Class.newInstance(Class.java:412)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
        ... 9 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.apache.nifi.ssl.SSLContextService$ClientAuth
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 14 common frames omitted
2020-11-02 12:55:38,374 INFO [Thread-1] org.apache.nifi.NiFi Initiating shutdown of Jetty web server...
2020-11-02 12:55:38,374 INFO [Thread-1] org.apache.nifi.NiFi Jetty web server shutdown completed (nicely or otherwise). 
```
I use docker cp command to copy corresponding NAR to /opt/nifi/nifi-current/lib folder

**Comment by bednar** [comment]
@viazovskyi thanks for issue we will take a look

**Comment by bednar** [comment]
Hi @viazovskyi,

Could you use version `1.12.1`? We currently don't have a build for `1.12.0`.

I've try use 1.12.1 by:

```console
docker run -d --name nifi -p 8080:8080 apache/nifi:1.12.1
wget https://github.com/influxdata/nifi-influxdb-bundle/releases/download/v1.8.0/nifi-influx-database-nar-1.8.0.nar
docker cp nifi-influx-database-nar-1.8.0.nar nifi:/opt/nifi/nifi-current/lib
docker restart nifi
```
and everything works correctly.

Regards

**Comment by viazovskyi** [comment]
Hi @bednar, it works, thank you! I close the issue.
